server:
    port: 8081

spring:
    application:
        name: ms-user
    datasource:
        url: jdbc:mysql://localhost:3308/user_db
        username: root
        password: Netec123
        driver-class-name: com.mysql.cj.jdbc.Driver
